package entity;
// Generated Dec 3, 2025 5:39:18 AM by Hibernate Tools 3.6.0



/**
 * Kendaraan generated by hbm2java
 */
public class Kendaraan  implements java.io.Serializable {


     private Integer id;
     private String merek;
     private String plat;
     private String warna;
     private Integer tahun;

    public Kendaraan() {
    }

    public Kendaraan(String merek, String plat, String warna, Integer tahun) {
       this.merek = merek;
       this.plat = plat;
       this.warna = warna;
       this.tahun = tahun;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMerek() {
        return this.merek;
    }
    
    public void setMerek(String merek) {
        this.merek = merek;
    }
    public String getPlat() {
        return this.plat;
    }
    
    public void setPlat(String plat) {
        this.plat = plat;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public Integer getTahun() {
        return this.tahun;
    }
    
    public void setTahun(Integer tahun) {
        this.tahun = tahun;
    }




}


